### ISSUE TITLE
how do you remove the config file if there is any or do  a clean install?

### ISSUE THREAD

**Issue by tikendraw** [Deminder/ShutdownTimer#24]
i want a clean install of this extension, i messed up with slider, small adjustment jumps hours across, tried setting the scale , it won't work. reinstalled it then it used old config again.  so

**"How do i clean install this extension?"**
or
**"How to remove the local config for this extension?"**

**Comment by Deminder** [comment]
*I hope ChatGPT can help you. I asked  "How to reset gnome extension settings to default values?":*

To reset GNOME extension settings to their default values, you can follow these steps:

1. **Locate the Extension's Directory**:
   - Extensions are typically stored in two places:
     - User-specific extensions: `~/.local/share/gnome-shell/extensions/`
     - System-wide extensions: `/usr/share/gnome-shell/extensions/`

2. **Identify the Extension**:
   - Find the directory corresponding to the extension you want to reset. The directory names usually include the extension's name or UUID.

3. **Reset Settings Using dconf**:
   - Open a terminal.
   - Use the `dconf reset` command to reset the settings of the extension. Extensions usually store their settings under the schema path `org.gnome.shell.extensions.<extension-name>`. Replace `<extension-name>` with the actual name or ID of the extension.
   - For example, to reset an extension named `example-extension`, you would run:
     ```bash
     dconf reset -f /org/gnome/shell/extensions/example-extension/
     ```

4. **Restart GNOME Shell**:
   - After resetting the settings, you need to restart GNOME Shell for the changes to take effect. You can do this by pressing `Alt+F2`, typing `r`, and pressing Enter. On Wayland, you may need to log out and log back in instead.

5. **Alternative: Gnome Extensions App**:
   - If you prefer a graphical method, you can use the GNOME Extensions app to disable and re-enable the extension, which might reset its settings in some cases.
   - Open the GNOME Extensions app, find the extension, disable it, and then enable it again.

6. **Manual Reset**:
   - If the extension stores its configuration in a specific configuration file, you can manually delete or edit this file. Configuration files for user-specific settings are often found in `~/.config` or `~/.local/share`.

### Example of Manual Reset:

1. **Navigate to the Configuration Directory**:
   - Go to `~/.config` or `~/.local/share` and find the directory or file related to the extension.

2. **Delete or Modify the Configuration File**:
   - If you find a specific configuration file, you can delete it to reset the settings. Alternatively, you can open it in a text editor and manually reset the values to their defaults.

3. **Restart GNOME Shell**:
   - Restart GNOME Shell using the `Alt+F2` method or by logging out and back in.

By following these steps, you should be able to reset the settings of your GNOME extensions to their default values.
