### ISSUE TITLE
Start an app after waking PC up.

### ISSUE THREAD

**Issue by tux-ware** [Deminder/ShutdownTimer#3]
Could you add an option to start an app after waking PC up, so that it can play a song or start an internet radio?

**Comment by Deminder** [comment]
Hi,
you can [automatically run program on Linux startup](https://www.simplified.guide/linux/automatically-run-program-on-startup#automatically-run-program-on-gnome-startup) by adding a user systemd unit such as `~/.config/systemd/user/my-script.service` and enabling it with `systemctl --user enable my-script.service` or if it is a desktop app, add it to the startup apps in `gnome-tweaks`.

If you want the script to only start after a shutdown+wake by the ShutdownTimer, you could consider setting some flag (such as by creating an empty file somewhere) via the check command feature. Then your a startup script could play a song only if the flag is set.

Please elaborate on the details of how you would like this to be implemented in case you really want this feature.

**Comment by Deminder** [comment]
This is probably a task better suited for other extensions:
https://github.com/hardpixel/systemd-manager or https://github.com/rovellipaolo/gnome-shell-extension-sermon
