### ISSUE TITLE
Feature Request: Specific Time Selection

### ISSUE THREAD

**Issue by Razinal** [Deminder/ShutdownTimer#5]
Hi,

I Love using your extension for gnome 43 but working out the exact time to enter in the extension for waking up/suspending always a little hard.
If possible I would like to be able to specify the exact time (e.g. 23:00:00) instead of calculating the required hours and minutes.

Thank you for your hard work.

**Comment by Deminder** [comment]
Hi @Razinal,
Glad to hear that you like the extension :slightly_smiling_face:

I like the idea but I'm not sure how it should work, excactly.
Maybe there could be an extra `reference-start-time` (e.g. `"23:00:00"`) option under `Timer Input` for `Shutdown` and `Wake`.
A simple string input might do the job?
By default `reference-start-time` would be empty (or `now`), indicating that the timer action should be relative to the current time as before.
Additionally, if some `reference-start-time` value is specified the slider should show the exact timestamp. 

- With `reference-start-time="23:00:00"` and slider at `0%` it would just show  `"23:00:00"`. 
- With slider at `25%` and maximum minutes at `120` would show `"23:30:00"`.

Let me know, if this sounds good. 

In any case, it will be some time until I work on this.

**Comment by Razinal** [comment]
I Love it.
Thanks for considering this.
