### ISSUE TITLE
Add activating the screensaver and hibernation as timer actions

### ISSUE THREAD

**Issue by bremaya** [Deminder/ShutdownTimer#7]
Is it possible to add an option for us to enter custom shutdown options like the option to hibernate or blank the screen? Thanks for your time and work in this extension!

**Comment by Deminder** [comment]
Hi @bremaya,

if you are asking for additional `screensaver,hibernate` timer actions beside the existing ones `poweroff,reboot,suspend`, this is certainly possible. 

I think this would fit well into this extension. Further, there is already [an extension providing hibernate](https://github.com/arelange/gnome-shell-extension-hibernate-status) without a timer.  An `hybridsleep` action might also make sense.
